In [1]:
import pandas as pd
import numpy as np
from faker import Faker

df = pd.read_csv('ibm_telco.csv')
print(df.shape)
df.head()

(7043, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
fake = Faker('tr_TR')

# Name (cinsiyete göre)
def generate_name(gender):
    if gender == 'Male':
        first = fake.first_name_male()
        last = fake.last_name_male()
    else:
        first = fake.first_name_female()
        last = fake.last_name_female()
    return f"{first} {last}"

df['Name'] = df['gender'].apply(generate_name)

# Age (18-80 arası mantıklı bir dağılım)
np.random.seed(42)
df['Age'] = np.random.randint(18, 81, size=len(df))

# SupportTicketCount (TechSupport'a bağlı Poisson)
df['SupportTicketCount'] = np.where(
    df['TechSupport'] == 'No',
    np.random.poisson(lam=3, size=len(df)),
    np.random.poisson(lam=1, size=len(df))
)

df[['customerID', 'gender', 'Name', 'Age', 'SupportTicketCount']].head(10)

   customerID  gender               Name  Age  SupportTicketCount
0  7590-VHVEG  Female  Mümtaze Karadeniz   56                   5
1  5575-GNVDE    Male    İyiyürek Şensoy   69                   3
2  3668-QPYBK    Male     Gürarda Durmuş   46                   8
3  7795-CFOCW    Male    Altınışın Duran   32                   2
4  9237-HQITU  Female       Arziye Duran   60                   4
5  9305-CDSKC  Female    Güverçin Arslan   25                   6
6  1452-KIOVK    Male  Abdurrahman Ergül   78                   5
7  6713-OKOMC  Female     Damlanur Duran   38                   1
8  7892-POOKP  Female     Cemiyle Arslan   56                   0
9  6388-TABGU    Male    Erksoy Yorulmaz   75                   3

In [4]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
print(df['TotalCharges'].isnull().sum())

11

In [5]:
df.to_csv('telecom_ibm_processed.csv', index=False)